database:
  driverClass: org.h2.Driver
  user: polten
  password: polten
  url: jdbc:h2:./buildPolten/h2db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.yunspace.dropwizard: DEBUG
    org.hibernate.SQL: ALL

  appenders:
    - type: console